version: "3.9"

services:
  telerix:
    image: fill205/telerix:latest
    container_name: telerix
    hostname: telerix
    ports:
      - "9000:80"
    restart: always
    volumes:
      - data:/Telerix-master
      - asterisk:/etc/asterisk
      - ssh_data:/etc/ssh
volumes:
  data: {}
  asterisk: {}
  ssh_data: {}

networks:
     default:
      external: 
        name: local